import React from 'react'
import Head from 'next/head'

import { Container, Content } from '../styles/pages/Home'
import Login from '../components/Login'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>prisma.focus | Prisma Systems</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Container>
          <Content>
            <img src="/svg/logo_white.svg" alt="Logo do app Prisma Systems" />

            <div className="login">
              <Login />
            </div>
          </Content>
        </Container>
      </main>
    </div>
  )
}

export default Home
