import React, { useContext, useEffect } from 'react'
import Head from 'next/head'

import Login from '../components/Login'

import { Container, Content } from '../styles/pages/Home'
import { AuthenticationContext } from '../contexts/AuthenticationContext'
import { useRouter } from 'next/router'

const Home: React.FC = () => {
  // const { UserConected } = useContext(AuthenticationContext)

  // const router = useRouter()

  // useEffect(() => {
  //   if (UserConected) {
  //     router.push(`/challenges/${UserConected.id}`)
  //   }
  // }, [UserConected])

  return (
    <div>
      <Head>
        <title>prisma.focus | Prisma Systems</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Container>
          <Content>
            <img src="/svg/logo_white.svg" alt="Logo do app Prisma Systems" />

            <div className="login">
              <Login />
            </div>
          </Content>
        </Container>
      </main>
    </div>
  )
}

export default Home
