import React from 'react'
import Head from 'next/head'
import { Container } from '../styles/pages/Home'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Setup Prisma Systems</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Container>
          <img src="/svg/icone.svg" alt="Logo Prisma Systems" />
          <h1>
            Setup <span>Prisma Systems</span>
          </h1>
          <p>
            Estrutura pronta para desenvolvimento de projetos utilizando React e
            Next com TypeScript.
          </p>
        </Container>
      </main>
    </div>
  )
}
