import React from 'react'
import Head from 'next/head'

import { AnimatePresence, motion } from 'framer-motion'

import Profile from '../components/Profile'
import MenuSideBar from '../components/MenuSideBar'

import { Container, Content } from '../styles/pages/Leaderboard'

const Leaderboard: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>Leaderboard | prisma.focus</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <MenuSideBar />

      <AnimatePresence>
        <motion.div
          initial={{ y: 60, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          exit={{ y: -60, opacity: 0 }}
          transition={{ duration: 0.3 }}
        >
          <Content>
            <div className="leaderboardUsers">
              <h1>Leaderboard</h1>
              <table>
                <tr className="titleTableLeaderboard">
                  <th id="titlePositionUser">POSIÇÃO</th>
                  <th id="titleProfileUser">USUÁRIO</th>
                  <th id="titleChallengesUser">DESAFIOS</th>
                  <th id="titleExperienceUser">EXPERIÊNCIA</th>
                </tr>
                <tr className="userInfos">
                  <td id="userId">1</td>
                  <td id="userProfile">
                    <Profile />
                  </td>
                  <td id="userChallengesCompleted">
                    <span className="highlightInfo">10</span> completados
                  </td>
                  <td id="userExperience">
                    <span className="highlightInfo">15000</span> xp
                  </td>
                </tr>
                <tr className="userInfos">
                  <td id="userId">2</td>
                  <td id="userProfile">
                    <Profile />
                  </td>
                  <td id="userChallengesCompleted">
                    <span className="highlightInfo">9</span> completados
                  </td>
                  <td id="userExperience">
                    <span className="highlightInfo">13900</span> xp
                  </td>
                </tr>

                <tr className="userInfos">
                  <td id="userId">3</td>
                  <td id="userProfile">
                    <Profile />
                  </td>
                  <td id="userChallengesCompleted">
                    <span className="highlightInfo">9</span> completados
                  </td>
                  <td id="userExperience">
                    <span className="highlightInfo">13900</span> xp
                  </td>
                </tr>
                <tr className="userInfos">
                  <td id="userId">4</td>
                  <td id="userProfile">
                    <Profile />
                  </td>
                  <td id="userChallengesCompleted">
                    <span className="highlightInfo">9</span> completados
                  </td>
                  <td id="userExperience">
                    <span className="highlightInfo">13900</span> xp
                  </td>
                </tr>
                <tr className="userInfos">
                  <td id="userId">5</td>
                  <td id="userProfile">
                    <Profile />
                  </td>
                  <td id="userChallengesCompleted">
                    <span className="highlightInfo">9</span> completados
                  </td>
                  <td id="userExperience">
                    <span className="highlightInfo">13900</span> xp
                  </td>
                </tr>
              </table>
            </div>
          </Content>
        </motion.div>
      </AnimatePresence>
    </Container>
  )
}

export default Leaderboard
