import React, { useEffect } from 'react'
import Head from 'next/head'

import { database } from '../services/firebase'

import { AnimatePresence, motion } from 'framer-motion'

import Profile from '../components/Profile'
import MenuSideBar from '../components/MenuSideBar'

import { Container, Content } from '../styles/pages/Leaderboard'
import UserLeaderboard from '../components/UserLeaderboard'
import { useGetLeaderboardData } from '../hooks/useGetLeaderboardData'

type DataOfDatabaseTypes = {
  LevelUser: number
  ExperienceUser: number
  TotalExperienceUser: number
  ChallengesCompleted: number
  name: string
  avatar: string
}

const Leaderboard: React.FC = () => {
  const { arrayChildren } = useGetLeaderboardData()

  return (
    <Container>
      <Head>
        <title>Leaderboard | prisma.focus</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <MenuSideBar />

      <AnimatePresence>
        <motion.div
          initial={{ y: 60, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          exit={{ y: -60, opacity: 0 }}
          transition={{ duration: 0.3 }}
        >
          <Content>
            <div className="leaderboardUsers">
              <h1>Leaderboard</h1>
              <table>
                <tr className="titleTableLeaderboard">
                  <th id="titlePositionUser">POSIÇÃO</th>
                  <th id="titleProfileUser">USUÁRIO</th>
                  <th id="titleChallengesUser">DESAFIOS</th>
                  <th id="titleExperienceUser">EXPERIÊNCIA</th>
                </tr>

                {arrayChildren
                  .map(data => {
                    return (
                      <UserLeaderboard
                        name={data.name}
                        avatar={data.avatar}
                        LevelUser={data.LevelUser}
                        ChallengesCompleted={data.ChallengesCompleted}
                        TotalExperienceUser={data.TotalExperienceUser}
                      />
                    )
                  })
                  .reverse()}
              </table>
            </div>
          </Content>
        </motion.div>
      </AnimatePresence>
    </Container>
  )
}

export default Leaderboard
